version: '3.7'

services:


  #Application logic...
  app_logic_apache:
    build: 
      context: .
      dockerfile:  './dockerfiles/apache_app_logic/Dockerfile'
    container_name: app_logic_apache
    hostname: app_logic_apache
    restart: always

    volumes:
      - ./App-Logic:/var/www/html/
    ports: 
      - "81:80"

    expose: 
      - "80"
    networks:
      default:
        ipv4_address: 172.18.1.8

  #Web app...80
  web_app_apache:
    build: 
      context: .
      dockerfile:  './dockerfiles/apache_web_app/Dockerfile'
    container_name: web_app_apache
    restart: always
    ports:
      - '80:80' #expose to localhost 
    volumes:
      - ./Web-App:/var/www/html/
    
    networks:
      default:
        ipv4_address: 172.18.1.9

  #mysql section..    
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    hostname: mysql_db
    restart: always
    ports:
      - '3306:3306' 
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_ROOT_HOST=172.18.1.5 # allows root connections from 172.18.1.5 which is keyrock 
      - MYSQL_DATABASE=idm
    networks:
      default:
        ipv4_address: 172.18.1.6
    volumes:
      - keyrock_data:/var/lib/mysql
      - ./backups/keyrock_backup:/docker-entrypoint-initdb.d 

  #phpmyadmin for mysql keyrock!!
  #phpmyadmin_keyrock:
  #  depends_on:
  #    - mysql_db
  #  image: phpmyadmin/phpmyadmin
  #  container_name: phpmyadmin_keyrock
  #  restart: always
  #  ports:
  #    - '4040:80' #expose in port 4040 to local machine 
  #  environment:
  #    PMA_HOST: mysql_db
  #    MYSQL_ROOT_PASSWORD: root_pass 
  #  networks:
  #    default:
  #      ipv4_address: 172.18.1.7 
    
  #mongo db section for data storage
  mongo_db_data_storage:
    image: mongo:latest
    restart: always
    hostname: mongo_db_data_storage
    container_name: mongo_db_data_storage
    ports: 
      - '27018:27017'  #expose in port 27017 to (local)27018
    volumes: 
      - mongo_data_storage_vol:/data/db   

    networks:
      default:
        ipv4_address: 172.18.1.10
  
  #import data to MONGO DATABASES!! 
  mongo_seed:
    container_name: mongo_seed
    image: mongo:latest
    links:
      - mongo_db_data_storage
    volumes:
    - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
        
  keyrock:
    image: fiware/idm:latest
    container_name: keyrock
    hostname: keyrock
    depends_on:
      - mysql_db
    ports:
      - "3005:3005" #expose to 3005 for admin!
      - "443:443" 
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql_db
      - IDM_DB_USER=root
      - IDM_DB_PASS=root_pass #password of root mysql!
      - IDM_HOST=http://localhost:3005
      - IDM_PORT=3005
      - IDM_ADMIN_USER=tdel
      - IDM_ADMIN_EMAIL=tdel@test.com
      - IDM_ADMIN_PASS=1234
   
    networks:
      default:
        ipv4_address: 172.18.1.5   
  
  #apache for data storage!
  data_storage_apache:
    build: 
      context: .
      dockerfile:  './dockerfiles/apache_data_storage/Dockerfile'
    container_name: dataStorage
    hostname: dataStorage
    restart: always

    expose: 
      - "80"  #for wilma!

    volumes:
      - ./Data-Storage:/var/www/html/
    
    networks:
      default:
        ipv4_address: 172.18.1.14
  
  
  #mongo db for orion
  mongo_db_orion:
    image: mongo:3.2
    hostname: mongo_db_orion
    container_name: mongo_db_orion
    command: --nojournal
    ports: 
      - '27017:27017'  #so we can connect with db
    volumes: 
      - orion_vol:/data/db
  
  #orion context broker
  orion:
    image: fiware/orion
    links:
      - mongo_db_orion
    command: -dbhost mongo_db_orion -logLevel DEBUG -noCache
    container_name: orion
    hostname: orion
    expose:
        - "1026"
    ports:
        - "1026:1026"
    networks:
      default:
        ipv4_address: 172.18.1.15 
  
  #wilma for orion!
  orion_proxy:
    image: fiware/pep-proxy 
    container_name: orion_proxy
    depends_on:
      - keyrock
    ports:
      - "1027:1027"
    expose:
      - "1027"
    environment: 
      - PEP_PROXY_APP_HOST=orion
      - PEP_PROXY_APP_PORT=1026
      - PEP_PROXY_PORT=1027
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=7ffbed02-ac0c-4784-8c52-2cf8d77f85fd
      - PEP_PROXY_USERNAME=pep_proxy_9c742db6-63d6-455e-ac2b-d6395fc8b514
      - PEP_PASSWORD=pep_proxy_f77c28ad-5ff8-4213-a500-340557670cd1
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=magic_key     
    networks:
      default:
        ipv4_address: 172.18.1.20


   #wilma for datastorage!
  data_storage_proxy:
    image: fiware/pep-proxy 
    container_name: data_storage_proxy
    depends_on:
      - keyrock
    ports:
      - "1028:1027"  #expose the default 1027 into 1028
    expose: 
      - "1028"
    environment: 
      - PEP_PROXY_APP_HOST=dataStorage
      - PEP_PROXY_APP_PORT=80
      - PEP_PROXY_PORT=1028
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=7ffbed02-ac0c-4784-8c52-2cf8d77f85fd
      - PEP_PROXY_USERNAME=pep_proxy_9c742db6-63d6-455e-ac2b-d6395fc8b514
      - PEP_PASSWORD=pep_proxy_f77c28ad-5ff8-4213-a500-340557670cd1
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=magic_key     
    networks:
      default:
        ipv4_address: 172.18.1.21
    
        
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes: 
  keyrock_data:
  mongo_data_storage_vol:
  orion_vol:
