version: '3.7'

services:
  #Application logic...
  app_logic_apache:
    build: 
      context: .
      dockerfile:  './dockerfiles/apache_app_logic/Dockerfile'
    container_name: app_logic_apache
    restart: always
    #dont expose this container!! no ports!
    networks:
      default:
        ipv4_address: 172.18.1.8

  #Web app...8081
  web_app_apache:
    build: 
      context: .
      dockerfile:  './dockerfiles/apache_web_app/Dockerfile'
    container_name: web_app_apache
    restart: always
    ports:
      - '80:80' #expose to localhost
    
    networks:
      default:
        ipv4_address: 172.18.1.9

  #mysql section..    
  mysql_db:
    build: 
      context: './dockerfiles/mysql/'
    container_name: mysql_db
    hostname: mysql_db
    restart: always
    ports:
      - '3306:3306' 
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_ROOT_HOST=172.18.1.5 # allows root connections from 172.18.1.5 which is keyrock
      
    networks:
      default:
        ipv4_address: 172.18.1.6

    volumes:
      - mysql_dat:/var/lib/mysql  #all the contents of /var/lib/mysql will be permently saved to mysql_dat volume
      #- docker-entrypoint-initdb.d #to init the db
    
  #phpmyadmin for mysql keyrock!!
  phpmyadmin_keyrock:
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_keyrock
    restart: always
    ports:
      - '4040:80' #expose in port 4040 to local machine 
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root_pass 
    networks:
      default:
        ipv4_address: 172.18.1.7 

  #mongo db section...
  mongo_db_data_storage:
    build: 
      context: './dockerfiles/mongo_db_data_storage/'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass
    container_name: mongo_db_data_storage
    ports: 
      - '27017:27017'
    volumes: 
      - mongo_db_data_storage:/data/db
    networks:
      default:
        ipv4_address: 172.18.1.10

  #mongo-express for MONGO DB 
  mongo_express_data_storage:
    image: mongo-express
    depends_on: 
      - mongo_db_data_storage
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_pass
      ME_CONFIG_MONGODB_SERVER: mongo_db_data_storage
    container_name: mongo_express_data_storage
    networks:
      default:
        ipv4_address: 172.18.1.11

  keyrock:
    image: fiware/idm:latest
    container_name: fiware-keyrock
    hostname: keyrock
    depends_on:
      - mysql_db
    ports:
      - "3005:3000" #expose to 3005 for signup!
      - "443:443" #for rest api
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql_db
      - IDM_DB_USER=root
      - IDM_DB_PASS=root_pass #password of root mysql!
      - IDM_HOST=http://localhost:3000
      - IDM_PORT=3000
      - IDM_ADMIN_USER=tdel
      - IDM_ADMIN_EMAIL=tdel@test.com
      - IDM_ADMIN_PASS=1234
   
    networks:
      default:
        ipv4_address: 172.18.1.5   
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes: 
  mysql_dat:
  mongo_db_data_storage:
  
